services:
  frontend:
    build: ./
    container_name: xnode-frontend
    restart: unless-stopped
    networks:
      - app-network
    expose:
      - "80"

networks:
  app-network:
    external: true
